config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :user_stocks, only: [:create, :destroy]
  resources :user_friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  root 'pages#index'
  get 'my_friends', to: 'users#my_friends'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'friendships#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks, dependent: :destroy
    has_many :users, through: :user_stocks
    validates :name, :ticker, presence: true

    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new( publishable_token: Rails.application.credentials.iex_client[:pub_key],
        secret_token: Rails.application.credentials.iex_client[:secret_key],
        endpoint: 'https://cloud.iexapis.com/v1' )
        begin
            new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.quote(ticker_symbol).latest_price)
        rescue => exception
            return false
        end
    end

    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first #Stock. is exempted because we are already in Stock class
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks, dependent: :destroy
  has_many :stocks, through: :user_stocks
  has_many :friendships, dependent: :destroy
  has_many :rev_friendships, dependent: :destroy, class_name: "Friendship", foreign_key: "friend_id"
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.search_user(param, uid)
    param.strip!
    result = (by_first_name(param, uid) + by_last_name(param, uid) + by_email(param, uid)).uniq
    return nil unless result
    result
  end
  def self.by_first_name(param, uid)
    query('first_name',param, uid)
  end
  def self.by_last_name(param, uid)
    query('last_name',param, uid)
  end
  def self.by_email(param, uid)
    query('email',param, uid)
  end
  def self.query(field, param, uid)
    where("#{field} LIKE ? AND id != ?","%#{param}%","#{uid}")
  end

  def friends_with?(friend_id)
    self.friends.where(id: friend_id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def search
        str = params[:friend]
        if(str.present?)
            @friends = User.search_user(str, current_user.id)
            if @friends.count>0
                respond_to do |format|
                    format.js { render partial: 'users/friend_info'}
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "No user found."
                    format.js { render partial: 'users/friend_info'}
                end

            end
        else
            respond_to do |format|
                flash.now[:alert] = "Enter name or email to search."
                format.js { render partial: 'users/friend_info'}
            end
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        str = params[:stock]
        if(str.present?)
            @stock = Stock.new_lookup(str)
            if @stock
                respond_to do |format|
                    format.js { render partial: 'users/stock_info'}
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "Enter valid symbol for stock to search."
                    format.js { render partial: 'users/stock_info'}
                end

            end
        else
            respond_to do |format|
                flash.now[:alert] = "Enter symbol for stock to search."
                format.js { render partial: 'users/stock_info'}
            end
        end
    end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
    def create
        current_user.friendships.build(friend_id: params[:friend])
        if current_user.save
            flash[:notice] = "You successfully added #{User.find(params[:friend]).full_name} to your friend list."
        else
            flash[:alert] = "Something went wrong."
        end
        redirect_to my_friends_path
    end

    def destroy
        user_friend = current_user.friendships.where(friend_id: params[:id]).first
        user_friend.destroy
        flash[:alert] = "#{User.find(params[:id]).full_name} was successfully removed from your list."
        redirect_to my_friends_path
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
            stock = Stock.new_lookup(params[:ticker])
            stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio."
        redirect_to my_portfolio_path
    end

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:alert] = "#{stock.ticker} was successfully removed from your portfolio."
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = @user.stocks
  end
  def my_friends
    @friends = current_user.friends
  end
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_list.html.erb
<div class="row">
    <div class="col-12 mx-auto">
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @friends.each do |record| %>
            <tr>
                <td><%= record.first_name %></td>
                <td><%= record.last_name %></td>
                <td><%= record.email %></td>
                <td class="text-center">
                    <%= link_to '<i class="fa fa-eye"></i>'.html_safe, user_path(record), class: 'btn btn-sm btn-primary', title: "View profile" %>
                    <%= link_to '<i class="fa fa-remove"></i>'.html_safe, user_friendship_path(record), method: :delete, title: "Remove from friends list", class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' } %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    </div>
</div>

app/views/layouts/_flashMessages.html.erb
<% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container">
        <%= link_to 'Finance Tracker', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to 'Portfolio', my_portfolio_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to 'Friends', my_friends_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to 'Profile', edit_user_registration_path, class: "nav-link" %></li>
                <% end %>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                    <% if user_signed_in? %>
                        <%= fa_icon 'user' %>
                        <%= current_user.full_name %>
                    <% else %>
                        Actions
                    <% end %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <% if user_signed_in? %>
                        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                    <% else %>
                        <%= link_to 'Login', new_user_session_path, class: "dropdown-item" %>
                        <%= link_to 'Signup', new_user_registration_path, class: "dropdown-item" %>
                    <% end %>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= render 'layouts/flashMessages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

app/views/stocks/_list.html.erb
<div class="row">
    <div class="col-10 mx-auto">
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">Ticker</th>
                <th scope="col">Name</th>
                <th scope="col">Last Price</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @tracked_stocks.each do |record| %>
            <tr>
                <td><%= record.ticker %></td>
                <td><%= record.name %></td>
                <td><%= record.last_price %></td>
                <td class="text-center">
                <% if current_user.id == @user.id %>
                    <%= link_to '<i class="fa fa-trash"></i>'.html_safe, user_stock_path(record), method: :delete, title: "Remove from stocks portfolio", class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' } %>
                <% elsif current_user.can_track_stock?(record.ticker) %>
                    <%= link_to user_stocks_path(ticker: record.ticker), { class: 'btn btn-info col-auto mx-auto mb-2' , method: :post, title: "Add stock to portfolio" } do %>
                        <i class="fa fa-heart-o"></i>
                    <% end %>
                <% else %>
                    <span class="col-auto mx-auto badge badge-secondary p-2 mb-2">You are already tracking
                    <% if !current_user.under_stock_limit? %>
                        10 stocks.
                    <% elsif current_user.stock_already_tracked?(record.ticker) %>
                        this stock.
                    <% end %>
                    </span>
                <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    </div>
</div>

app/views/users/_friend_info.html.erb
<div class="row">
    <div class="col-8 mx-auto">
        <%= render 'layouts/flashMessages' %>
    </div>
</div>
<div class="card card-body col-lg-6 mb-3 p-0 mx-auto">
    <table class="table mb-2">
        <thead>
            <tr>
                <th class="border-top-0">Name</th>
                <th class="border-top-0">Email</th>
                <th class="border-top-0">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @friends.each do |record| %>
            <tr>
                <td><%= record.full_name %></td>
                <td><%= record.email %></td>
                <td class="text-center">
                <%= link_to user_path(record), { class: 'col-auto btn btn-primary mb-2', title: "View profile" } do %>
                    <i class="fa fa-eye"></i>
                <% end %>
                <% if !current_user.friends_with?(record.id) %>
                    <%= link_to user_friendships_path(friend: record.id), { class: 'col-auto btn btn-secondary mb-2' , method: :post, title: "Add as friend" } do %>
                        <i class="fa fa-user-plus"></i>
                    <% end %>
                <% else %>
                    <span class="col-auto mx-auto badge badge-info p-2 mb-2">You are friends</span>
                <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/users/_friend_info.js.erb
document.getElementById("friend_view").innerHTML = '<%= escape_javascript(render 'users/friend_info.html') %>'

app/views/users/_stock_info.html.erb
<div class="row">
    <div class="col-8 mx-auto">
        <%= render 'layouts/flashMessages' %>
    </div>
</div>
<% if @stock %>
    <div class="card card-body col-lg-6 mb-3 p-0 mx-auto">
        <table class="table mb-2">
            <tbody>
                <tr>
                    <th class="border-top-0">Symbol</th>
                    <td class="border-top-0"><%= @stock.ticker %></td>
                </tr>
                <tr>
                    <th>Company</th>
                    <td><%= @stock.name %></td>
                </tr>
                <tr>
                    <th class="table_border_botttom">Latest Price</th>
                    <td class="table_border_botttom"><%= @stock.last_price %></td>
                </tr>
            </tbody>
        </table>
        <% if current_user.can_track_stock?(@stock.ticker) %>
            <%= link_to user_stocks_path(ticker: @stock.ticker), { class: 'btn btn-info col-2 mx-auto mb-2' , method: :post, title: "Add stock to portfolio" } do %>
                <i class="fa fa-heart-o"></i>
            <% end %>
        <% else %>
            <span class="col-auto mx-auto badge badge-secondary p-2 mb-2">You are already tracking
            <% if !current_user.under_stock_limit? %>
                10 stocks.
            <% elsif current_user.stock_already_tracked?(@stock.ticker) %>
                this stock.
            <% end %>
            </span>
        <% end %>
    </div>
<% end %>

app/views/users/_stock_info.js.erb
document.getElementById("stock_view").innerHTML = '<%= escape_javascript(render 'users/stock_info.html') %>'

app/views/users/my_friends.html.erb
<h1 class="display-4 text-secondary text-center">Friends List</h1>

<div class="row">
    <div class="col-10 mx-auto">
        <div class="mt-3">
            <h3 class="text-monospace text-info">Search Friends</h3>
            <%= form_tag search_friend_path, remote: true, method: :get do %>
                <div class="form-group">
                    <div class="row m-0">
                        <div class="col-11 p-0">
                            <%= text_field_tag :friend, nil, placeholder: 'Enter name or email', autofocus: true, class: 'form-control' %>
                        </div>
                        <div class="col-1 p-0">
                            <%= button_tag data: { :disable_with => "..." }, type: :submit, class: 'btn btn-info' do %>
                                <%= fa_icon 'search' %>
                            <% end %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <div id="friend_view">
        </div>
    </div>
</div>

<% if @friends %>
    <%= render 'friendships/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1 class="display-4 text-secondary text-center">My Portfolio</h1>

<div class="row">
    <div class="col-10 mx-auto">
        <div class="mt-3">
            <h3 class="text-monospace text-info">Search Stocks</h3>
            <%= form_tag search_stock_path, remote: true, method: :get do %>
                <div class="form-group">
                    <div class="row m-0">
                        <div class="col-11 p-0">
                            <%= text_field_tag :stock, nil, placeholder: 'Enter stock symbol', autofocus: true, class: 'form-control' %>
                        </div>
                        <div class="col-1 p-0">
                            <%= button_tag data: { :disable_with => "..." }, type: :submit, class: 'btn btn-info' do %>
                                <%= fa_icon 'search' %>
                            <% end %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <div id="stock_view">
        </div>
    </div>
</div>

<% if @tracked_stocks %>
    <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h3 class="text-center">Friend's Profile</h3>
<div class="row">
    <div class="col-8 mx-auto p-3">
        <div class="card card-body p-0">
            <table class="table mb-2">
                <tbody>
                    <tr>
                        <th class="border-top-0">Name</th>
                        <td class="border-top-0"><%= @user.full_name %></td>
                    </tr>
                    <tr>
                        <th class="table_border_botttom">Email</th>
                        <td class="table_border_botttom"><%= @user.email %></td>
                    </tr>
                </tbody>
            </table>
            <% if !current_user.friends_with?(@user.id) %>
                <%= link_to user_friendships_path(friend: @user.id), { class: 'btn btn-secondary col-auto mx-auto mb-2' , method: :post, title: "Add as friend" } do %>
                    <i class="fa fa-user-plus"></i>
                <% end %>
            <% else %>
                <span class="col-auto mx-auto badge badge-info p-2 mb-2">You are friends</span>
            <% end %>
        </div>
    </div>
</div>
<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% else %>
    <div class="row">
        <div class="col-auto mx-auto badge badge-secondary p-3">This user is not tracking any stocks.</div>
    </div>
<% end %>